apiVersion: apps/v1
kind: Deployment
metadata:
    name: glowjob-api-staging
    namespace: glowjob-staging
    labels:
        app: glowjob-api-staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: glowjob-api-staging
    template:
        metadata:
            labels:
                app: glowjob-api-staging
        spec:
            containers:
                - name: glowjob-api-staging
                  image: aimerisson/glowjob-api-staging:IMAGE_LABEL
                  ports:
                      - containerPort: 8000

                  env:
                      - name: ENV
                        value: "PROD"
                      -   name: POSTGRES_ENGINE
                          value: "django.db.backends.postgresql"
                      -   name: POSTGRES_NAME
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-secret
                                  key: POSTGRES_NAME
                      -   name: POSTGRES_USER
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-secret
                                  key: POSTGRES_USER
                      -   name: POSTGRES_PASSWORD
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-secret
                                  key: POSTGRES_PASSWORD
                      -   name: POSTGRES_HOST
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-secret
                                  key: POSTGRES_HOST
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: '250m'

