CREATE TABLE user_preference
(
  id      UUID NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT pk_userpreference PRIMARY KEY (id),
  CONSTRAINT fk_userpreference_on_user FOREIGN KEY (user_id) REFERENCES "user" (id)
  CONSTRAINT uc_userpreference_user UNIQUE (user_id)
);

CREATE TABLE contract_type
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  libelle            VARCHAR(255)                            NOT NULL,
  code               VARCHAR(255)                            NOT NULL,
  user_preference_id UUID                                    NOT NULL,
  CONSTRAINT pk_contracttype PRIMARY KEY (id),
  CONSTRAINT fk_contracttype_user_preference_id FOREIGN KEY (user_preference_id) REFERENCES user_preference (id);
);

CREATE TABLE job
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  libelle            VARCHAR(255)                            NOT NULL,
  code               VARCHAR(255)                            NOT NULL,
  user_preference_id UUID                                    NOT NULL,
  CONSTRAINT pk_job PRIMARY KEY (id),
  CONSTRAINT fk_job_on_user_preference FOREIGN KEY (user_preference_id) REFERENCES user_preference (id)
);

CREATE TABLE location
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  libelle            VARCHAR(255)                            NOT NULL,
  code               VARCHAR(255)                            NOT NULL,
  type               VARCHAR(255)                            NOT NULL,
  user_preference_id UUID                                    NOT NULL,
  CONSTRAINT pk_location PRIMARY KEY (id),
  CONSTRAINT fk_location_on_user_preference FOREIGN KEY (user_preference_id) REFERENCES user_preference (id)
);
